<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */

$this->headTitle('Listings - Kapitel 15');
$this->pageTitle('Listings - Kapitel 15');
?>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing1501">Listing 15.1</a></td>
<td><code>Module.php</code> für das <code>Application</code>-Modul</td>
</tr>
<tr>
<td><a href="/listing/listing1502">Listing 15.2</a></td>
<td>Konfigurationsdatei <code>module.config.php</code> für das <code>Application</code>-Modul</td>
</tr>
<tr>
<td><a href="/listing/listing1503">Listing 15.3</a></td>
<td><code>PageTitle</code> View-Helper zur Ausgabe von <code>H1</code>-Überschriften</td>
</tr>
<tr>
<td><a href="/listing/listing1504">Listing 15.4</a></td>
<td><code>ShowMessages</code> View-Helper zur Ausgabe von Meldungen</td>
</tr>
<tr>
<td><a href="/listing/listing1505">Listing 15.5</a></td>
<td>Factory für <code>ShowMessages</code> View-Helper</td>
</tr>
<tr>
<td><a href="/listing/listing1506">Listing 15.6</a></td>
<td><code>ShowForm</code> View-Helper zur Ausgabe von Formularen</td>
</tr>
<tr>
<td><a href="/listing/listing1507">Listing 15.7</a></td>
<td><code>Date</code> View-Helper zur Ausgabe von Datumswerten</td>
</tr>
<tr>
<td><a href="/listing/listing1508">Listing 15.8</a></td>
<td><code>ApplicationListener</code> zur Erweiterung des zweistufigen Layouts</td>
</tr>
<tr>
<td><a href="/listing/listing1509">Listing 15.9</a></td>
<td>Konfiguration der Layoutsegmente in der Template-Map</td>
</tr>
<tr>
<td><a href="/listing/listing1510">Listing 15.10</a></td>
<td>Layout View-Skript verwendet Layoutsegmente</td>
</tr>
<tr>
<td><a href="/listing/listing1511">Listing 15.11</a></td>
<td>Layout-Skript <code>layout/sidebar</code> für die Seitenleiste</td>
</tr>
<tr>
<td><a href="/listing/listing1512">Listing 15.12</a></td>
<td><code>Zend\Navigation</code> Konfiguration in <code>module.config.php</code></td>
</tr>
<tr>
<td><a href="/listing/listing1513">Listing 15.13</a></td>
<td><code>header.phtml</code> mit Ausgabe des Hauptmenüs</td>
</tr>
<tr>
<td><a href="/listing/listing1514">Listing 15.14</a></td>
<td><code>AboutController</code> für "Über uns" Seiten</td>
</tr>
<tr>
<td><a href="/listing/listing1515">Listing 15.15</a></td>
<td>View-Skript <code>/view/application/about/index.phtml</code></td>
</tr>
<tr>
<td><a href="/listing/listing1516">Listing 15.16</a></td>
<td>Anpassung <code>ApplicationListener</code> für Validatorennachrichten</td>
</tr>
<tr>
<td><a href="/listing/listing1517">Listing 15.17</a></td>
<td>Template zur Seitennavigation für <code>Zend\Paginator</code></td>
</tr>
<tr>
<td><a href="/listing/listing1518">Listing 15.18</a></td>
<td><code>StringToUrl</code> Filter, um Strings in URLs verwenden zu können</td>
</tr>
<tr>
<td><a href="/listing/listing1519">Listing 15.19</a></td>
<td><code>StringHtmlPurifier</code> Filter, um Strings mit HTMLPurifier zu säubern</td>
</tr>
<tr>
<td><a href="/listing/listing1520">Listing 15.20</a></td>
<td>Konfigurationsdatei <code>module.config.php</code> für eigene Filter</td>
</tr>
<tr>
<td><a href="/listing/listing1521">Listing 15.21</a></td>
<td>Geänderte <code>Module.php</code> zum Registrieren des <code>StringToUrl</code> Filters</td>
</tr>
</tbody>
</table>
