<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 15.6 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 15.6');
$this->pageTitle('Listing 15.6');
?>
<h3><code>ShowForm</code> View-Helper zur Ausgabe von Formularen</h3>
<pre>
&lt;?php
namespace Application\View\Helper;

use Zend\Form\Element\Hidden;
use Zend\Form\Element\Csrf;
use Zend\Form\Element\Submit;
use Zend\Form\Form;
use Zend\View\Helper\AbstractHelper;

class ShowForm extends AbstractHelper
{
    public function __invoke(Form $form, $url, $class = 'form-horizontal')
    {
        $form-&gt;setAttribute('action', $url);
        $form-&gt;setAttribute('class', $class);
        $form-&gt;prepare();
        
        $output = $this-&gt;getView()-&gt;form()-&gt;openTag($form);
        
        $submitElements = array();
        
        foreach ($form as $element) {
            if ($element instanceof Submit) {
                $submitElements[] = $element;
            } elseif ($element instanceof Csrf 
                || $element instanceof Hidden
            ) {
                $output .= $this->getView()->formElement($element);
            } else {
                $element-&gt;setLabelAttributes(array('class' =&gt; 'control-label'));
                
                $output .= '&lt;div class="control-group"&gt;';
                $output .= $this-&gt;getView()-&gt;formLabel($element);
                $output .= '&lt;div class="controls"&gt;';
                $output .= $this-&gt;getView()-&gt;formElement($element);
                $output .= $this-&gt;getView()-&gt;formElementErrors($element);
                $output .= '&lt;/div&gt;';
                $output .= '&lt;/div&gt;';
            }
        }
        
        $output .= '&lt;div class="form-actions"&gt;';
        foreach ($submitElements as $element) {
            $output .= $this->getView()->formElement($element) . '&nbsp;';
        }
        $output .= '&lt;/div&gt;';
        
        $output .= $this-&gt;getView()-&gt;form()-&gt;closeTag();
        
        return $output;
    }
}
</pre>
