<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 15.20 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 15.20');
$this->pageTitle('Listing 15.20');
?>
<h3>Konfigurationsdatei <code>module.config.php</code> für eigene Filter</h3>
<pre>
&lt;?php
return array(
    [...]
    
    'filters' => array(
        'invokables'=> array(
            'stringToUrl'        => 'Application\Filter\StringToUrl',
            'stringHtmlPurifier' => 'Application\Filter\StringHtmlPurifier',
        ),
    ),
    
    [...]
);
</pre>