<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 15.19 view script
 * 
 * @package    Application
 */

use Zend\Filter\StaticFilter;

$this->headTitle('Listing 15.19');
$this->pageTitle('Listing 15.19');
?>
<h3><code>StringHtmlPurifier</code> Filter, um Strings mit HTMLPurifier zu säubern</h3>
<pre>
&lt;?php
namespace Application\Filter;

use Zend\Filter\AbstractFilter;
use \HTMLPurifier;
use \HTMLPurifier_Bootstrap;
use \HTMLPurifier_Config;

class StringHtmlPurifier extends AbstractFilter
{
    protected $htmlPurifer = null;

    public function __construct()
    {
        if (!class_exists('HTMLPurifier_Bootstrap', false)) {
            spl_autoload_register(array('HTMLPurifier_Bootstrap', 'autoload'));
        }
        $config = HTMLPurifier_Config::createDefault();
        $config->set(
            'Cache.SerializerPath', LUIGI_ROOT . '/data/htmlpurifier'
        );
        $def = $config->getHTMLDefinition(true);
        $this->htmlPurifer = new HTMLPurifier($config);
    }
 
    public function filter($value)
    {
        return $this->htmlPurifer->purify($value);
    }
}
</pre>
