<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 15.17 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 15.17');
$this->pageTitle('Listing 15.17');
?>
<h3>Template zur Seitennavigation für <code>Zend\Paginator</code></h3>
<pre>
&lt;div class="pagination pagination-centered"&gt;
&lt;ul&gt;
&lt;?php if (isset($this-&gt;previous)): ?&gt;
&lt;?php $url = $this-&gt;url($this-&gt;route, array('page' =&gt; $this-&gt;previous)); ?&gt;
&lt;li&gt;&lt;a href="&lt;?php echo $url; ?&gt;"&gt;&laquo;&lt;/a&gt;&lt;/li&gt;
&lt;?php else: ?&gt;
&lt;li class="disabled"&gt;&lt;a&gt;&laquo;&lt;/a&gt;&lt;/li&gt;
&lt;?php endif; ?&gt;
&lt;?php foreach ($this-&gt;pagesInRange as $page) :?&gt;
&lt;?php if ($page != $this-&gt;current): ?&gt;
&lt;?php $url = $this-&gt;url($this-&gt;route, array('page' =&gt; $page)); ?&gt;
&lt;li&gt;&lt;a href="&lt;?php echo $url; ?&gt;"&gt;&lt;?php echo $page; ?&gt;&lt;/a&gt;&lt;/li&gt;
&lt;?php else: ?&gt;
&lt;li class="active"&gt;&lt;a&gt;&lt;?php echo $page; ?&gt;&lt;/a&gt;&lt;/li&gt;
&lt;?php endif; ?&gt;
&lt;?php endforeach; ?&gt;
&lt;?php if (isset($this-&gt;next)): ?&gt;
&lt;?php $url = $this-&gt;url($this-&gt;route, array('page' =&gt; $this-&gt;next)); ?&gt;
&lt;li&gt;&lt;a href="&lt;?php echo $url; ?&gt;"&gt;&raquo;&lt;/a&gt;&lt;/li&gt;
&lt;?php else: ?&gt;
&lt;li class="disabled"&gt;&lt;a&gt;&raquo;&lt;/a&gt;&lt;/li&gt;
&lt;?php endif; ?&gt;
&lt;/ul&gt;
&lt;/div&gt;
</pre>
