<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 15.18 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 15.18');
$this->pageTitle('Listing 15.18');
?>
<h3><code>StringToUrl</code> Filter, um Strings in URLs verwenden zu können</h3>
<pre>
&lt;?php
namespace Application\Filter;

use Zend\Filter\AbstractFilter;

class StringToUrl extends AbstractFilter
{
    protected $_delimiter = null;

    public function __construct($delimiter = '-')
    {
        $this->_delimiter = $delimiter;
    }

    public function filter($value)
    {
        $search = array(
            '= |\(|\)|\/|\,|\'|´|\-|\_|`|\.|\@|\||&=',
            '=á|à|â|ã|ą|ă|ā|Â|Á|À|Ã|Ą|Ă|Ā=i',
            '=å|Å=i',
            '=ä|æ|Ä|Æ=i',
            '=ç|ć|č|ċ|ĉ|Ç|Ć|Č|Ċ|Ĉ=i',
            '=ď|Ď=i',
            '=ð|Ð=i',
            '=é|è|ê|ë|ę|ě|ē|ė|Ê|É|È|Ë|Ę|Ě|Ē|Ė=i',
            '=ğ|ġ|ĝ|ģ|Ğ|Ġ|Ĝ|Ģ=i',
            '=ħ|ĥ|Ħ|Ĥ=i',
            '=í|ì|î|ï|ı|ĩ|į|ï|Î|Í|Ì|Ï|İ|Ĩ|Į|Ī=i',
            '=ĵ|Ĵ=i',
            '=ķ|ĸ|Ķ=i',
            '=ł|ľ|ĺ|ļ|Ł|Ľ|Ĺ|Ļ=i',
            '=ñ|ń|ň|ņ|Ñ|Ń|Ň|Ņ=i',
            '=ó|ò|ô|õ|ő|ō|Ô|Ó|Ò|Õ|Ő|Ō=i',
            '=ö|ø|Ö|Ø=i',
            '=ŕ|ř|ŗ|Ŕ|Ř|Ŗ=i',
            '=š|ś|ş|ŝ|Š|Ś|Ş|Ŝ=i',
            '=ß=i',
            '=ť|ţ|ŧ|Ť|Ţ|Ŧ=i',
            '=Þ|þ=i',
            '=ú|ù|û|ů|ű|ŭ|ų|ũ|ū|Û|Ú|Ù|Ů|Ű|Ŭ|Ų|Ũ|Ū=i',
            '=ü|Ü=i',
            '=ý|ÿ|Ý|Ÿ=i',
            '=ź|ž|ż|Ź|Ž|Ż=i',
        );
        
        $replace = array(
            $this->_delimiter,
            'a', 'aa', 'ae', 'c', 'd', 'dj', 'e', 'g', 'h', 'i', 'j', 'k', 'l',
            'n', 'o', 'oe', 'r', 's', 'ss', 't', 'th', 'u', 'ue', 'y', 'z',
        );
        
        $value = preg_replace($search, $replace, (string) $value);
        
        $value = preg_replace(
            '=[^a-z0-9' . $this->_delimiter . ']*=i', '', $value
        );
        
        $value = preg_replace(
            '=' . $this->_delimiter . '+=', $this->_delimiter, $value
        );
        
        $value = preg_replace(
            '=^' . $this->_delimiter . '|' . $this->_delimiter . '$=', 
            '', $value
        );
        
        return strtolower($value);
    }
}
</pre>
