<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 15.2 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 15.2');
$this->pageTitle('Listing 15.2');
?>
<h3>Konfigurationsdatei <code>module.config.php</code> für das <code>Application</code>-Modul</h3>
<pre>
&lt;?php
return array(
    'router' => array(
        'routes' => array(
            'home' => array(
                'type' => 'Literal',
                'options' => array(
                    'route'    => '/',
                    'defaults' => array(
                        'controller' => 'index',
                        'action'     => 'index',
                    ),
                ),
            ),
            'application' => array(
                'type'    => 'segment',
                'options' => array(
                    'route'    => '[/:controller[/:action[/:page]]]',
                    'constraints' => array(
                        'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'action'     => '[a-zA-Z][a-zA-Z0-9_-]*',
                        'page'       => '[0-9_-]*',
                    ),
                    'defaults' => array(
                        'controller' => 'index',
                        'action'     => 'index',
                        'page'       => '1',
                    ),
                ),
            ),
        ),
    ),
    
    'controllers' => array(
        'invokables' => array(
            'index'   => 'Application\Controller\IndexController',
            'listing' => 'Application\Controller\ListingController',
            'about'   => 'Application\Controller\AboutController',
        ),
    ),
    
    [...]
    
    'view_helpers' => array(
        'invokables'=> array(
            'pageTitle'    => 'Application\View\Helper\PageTitle',
            'showForm'     => 'Application\View\Helper\ShowForm',
            'date'         => 'Application\View\Helper\Date',
        ),
        'factories'=> array(
            'showMessages' => 'Application\View\Helper\ShowMessagesFactory',
        ),
    ),
    
    'view_manager' => array(
        'display_not_found_reason' => true,
        'display_exceptions'       => true,
        'doctype'                  => 'HTML5',
        'not_found_template'       => 'error/404',
        'exception_template'       => 'error/index',
        'template_map' => array(
            'layout/layout'           => __DIR__ . '/../view/layout/layout.phtml',
            [...]
            'application/index/index' => __DIR__ . '/../view/application/index/index.phtml',
            'pagination/sliding'      => __DIR__ . '/../view/pagination/sliding.phtml',
            'error/404'               => __DIR__ . '/../view/error/404.phtml',
            'error/index'             => __DIR__ . '/../view/error/index.phtml',
        ),
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),
    
    'session' => array(
        'save_path' => realpath(LUIGI_ROOT . '/data/session'),
        'name'      => 'LUIGI_SESSION',
    ),
    
    [...]
);
</pre>
