<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 15.9 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 15.9');
$this->pageTitle('Listing 15.9');
?>
<h3>Konfiguration der Layoutsegmente in der Template-Map</h3>
<pre>
&lt;?php
return array(
    [...]
        
    'view_manager' => array(
        [...]
        'template_map' => array(
            'layout/layout'  => __DIR__ . '/../view/layout/layout.phtml',
            'layout/header'  => __DIR__ . '/../view/layout/header.phtml',
            'layout/footer'  => __DIR__ . '/../view/layout/footer.phtml',
            'layout/sidebar' => __DIR__ . '/../view/layout/sidebar.phtml',
            [...]
        ),
        [...]
    ),
    
    [...]
);
</pre>
