<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 15.21 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 15.21');
$this->pageTitle('Listing 15.21');
?>
<h3>Geänderte <code>Module.php</code> zum Registrieren des <code>StringToUrl</code> Filters</h3>
<pre>
&lt;?php
namespace Application;

use Zend\Filter\StaticFilter;
use Zend\Validator\StaticValidator;

class Module implements 
    BootstrapListenerInterface,
    ConfigProviderInterface,
    AutoloaderProviderInterface
{
    public function onBootstrap(EventInterface $e)
    {
        [...]
        
        $filterManager    = $serviceManager->get('FilterManager');
        $validatorManager = $serviceManager->get('ValidatorManager');
        
        StaticFilter::setPluginManager($filterManager);
        StaticValidator::setPluginManager($validatorManager);
    }
}
</pre>