<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch 'Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung'
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 15.13 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 15.13');
$this->pageTitle('Listing 15.13');
?>
<h3><code>header.phtml</code> mit Ausgabe des Hauptmenüs</h3>
<pre>
&lt;?php
$this->navigation('navigation')->menu()->setUlClass('nav');
echo $this->navigation('navigation')->menu()->renderMenu(
    null, array('maxDepth' => 0)
);
</pre>
