<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 15.3 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 15.3');
$this->pageTitle('Listing 15.3');
?>
<h3><code>PageTitle</code> View-Helper zur Ausgabe von <code>H1</code>-Überschriften</h3>
<pre>
&lt;?php
namespace Application\View\Helper;

use Zend\View\Helper\HeadTitle;

class PageTitle extends HeadTitle
{
    protected $regKey     = 'Application_View_Helper_PageTitle';
    protected $autoEscape = false;
    protected $separator  = ' &raquo; ';

    public function toString($indent = null)
    {
        $output = parent::toString($indent);
        $output = str_replace(
            array('&lt;title&gt;', '&lt;/title&gt;'), array('&lt;h1&gt;', '&lt;/h1&gt;'), $output
        );
        
        return $output;
    }
}
</pre>
