<?php 
/**
 * ZF2 Buch Kapitel 15
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 15.16 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 15.16');
$this->pageTitle('Listing 15.16');
?>
<h3>Anpassung <code>ApplicationListener</code> für Validatorennachrichten</h3>
<pre>
&lt;?php
namespace Application\Listener;

use Zend\Mvc\I18n\Translator;
use Zend\Validator\AbstractValidator;

class ApplicationListener implements ListenerAggregateInterface
{
    public function attach(EventManagerInterface $events)
    {
        [...]
        
        $this->listeners[] = $events->attach(
            MvcEvent::EVENT_DISPATCH, 
            array($this, 'addValidatorTranslations'), 
            100
        );
    }

    public function addValidatorTranslations(EventInterface $e)
    {
        $baseDir = LUIGI_ROOT . '/module/Application/language';
        
        $translator = Translator::factory(array(
            'locale'                    => 'de',
            'translation_file_patterns' => array(
                array(
                    'type'        => 'phpArray',
                    'base_dir'    => $baseDir,
                    'pattern'     => 'Zend_Validate.php',
                    'text_domain' => 'default',
                ),
            )
        ));
        
        AbstractValidator::setDefaultTranslator($translator);
    }
}
</pre>
